Profile page skeleton with routing.
SkyPedal/SkyPedal pull request #25
Opened 2024-08-05 15:46 UTC by sammyswe

2024-08-05 16:09 UTC, WilliamMoolman requested changes

2024-08-05 16:09 UTC, WilliamMoolman commented on src/App.css
> +
We can remove this whitespace

2024-08-05 16:09 UTC, WilliamMoolman commented on src/components/Placeholder.jsx
What does placeholder mean? Can we rename this SignIn.jsx?

2024-08-06 10:01 UTC, sammyswe commented on src/components/Placeholder.jsx
Yes on it.

2024-08-06 11:59 UTC, WilliamMoolman approved these changes

2024-08-07 15:46 UTC, Neutralas approved these changes
looks good!

2024-08-07 16:37 UTC, merged