Feat activity feed Template
SkyPedal/SkyPedal pull request #26
Opened 2024-08-05 15:53 UTC by bertiep

This is just a template for the activity feed. Will add in database implementation in 2nd sprint.

2024-08-05 16:04 UTC, WilliamMoolman requested changes
Otherwise lgtm

2024-08-06 14:56 UTC, Neutralas requested changes

2024-08-06 14:56 UTC, Neutralas commented on src/components/ActivityFeed.jsx
> +    <div className="max-w-4xl mx-auto p-6 bg-gray-100 h-screen">
extracting an activity to be its own component would be a solid addition

2024-08-06 14:58 UTC, WilliamMoolman approved these changes

2024-08-08 15:18 UTC, Neutralas approved these changes
great change, thank you!

2024-08-08 15:23 UTC, merged