feat: add drag and drop GPX file uploader
SkyPedal/SkyPedal pull request #31
Opened 2024-08-06 15:40 UTC by WilliamMoolman

closes #6

2024-08-07 13:20 UTC, sammyswe approved these changes

2024-08-08 14:42 UTC, Neutralas requested changes

2024-08-08 14:42 UTC, Neutralas commented on cypress/fixtures/example.json
we don't need this

2024-08-08 14:53 UTC, Neutralas approved these changes
looks good!

2024-08-08 14:53 UTC, merged